export const GUESS_WHO_IDENTITIES = [
  // historical figures
  "Albert Einstein",
  "Cleopatra",
  "Abraham Lincoln",
  "Leonardo da Vinci",
  "Napoleon Bonaparte",
  "Martin Luther King Jr.",
  "Mahatma Gandhi",
  "Marie Curie",
  "William Shakespeare",
  "Genghis Khan",
  // celebrities & athletes
  "Taylor Swift",
  "Beyoncé",
  "Tom Hanks",
  "Cristiano Ronaldo",
  "Lionel Messi",
  "Dwayne Johnson",
  "Rihanna",
  "Michael Jordan",
  "Oprah Winfrey",
  "Elon Musk",
  "LeBron James",
  "Serena Williams",
  "Tom Cruise",
  "Will Smith",
  "Adele",
  "Ed Sheeran",
  "BTS",
  "Blackpink",
  // fictional characters
  "Harry Potter",
  "Spider-Man",
  "Batman",
  "Elsa",
  "Sherlock Holmes",
  "Shrek",
  "Mickey Mouse",
  "Darth Vader",
  "SpongeBob SquarePants",
  "Homer Simpson",
  "Iron Man",
  "Wonder Woman",
  "Pikachu",
  "Gandalf",
  "Luke Skywalker",
  "Buzz Lightyear",
  // random objects
  "Toaster",
  "Umbrella",
  "Traffic Light",
  "Pineapple",
  "Rubber Duck",
  "Bowling Ball",
  "Cactus",
  "Disco Ball",
  "Flashlight",
  "Snow Globe",
  "Fire Hydrant",
  "Vending Machine",
] as const;
