export const MOLE_TOPICS = [
  "Beach Day",
  "Birthday Party",
  "Camping Trip",
  "Study Group",
  "Road Trip",
  "Grocery Store",
  "Wedding",
  "Hospital",
  "The Gym",
  "Coffee Shop",
  "Airport",
  "Concert",
  "Zoo",
  "Library",
  "Movie Theater",
  "Restaurant",
  "Ski Trip",
  "Bowling Alley",
  "Karaoke Night",
  "Fishing Trip",
  "Museum",
  "Amusement Park",
  "Barbecue",
  "Football Game",
  "Yoga Class",
  "Ice Cream Shop",
  "Farmers Market",
  "Spa Day",
  "Halloween Party",
  "New Year's Eve",
  "Graduation",
  "Job Interview",
  "First Date",
  "Family Reunion",
  "Company Retreat",
  "Video Game Night",
  "Board Game Night",
  "Potluck Dinner",
  "Garage Sale",
  "Costume Party",
] as const;
